const chapterNames={1:'Глава первая',2:'Глава вторая',3:'Глава третья',4:'Глава четвёртая',5:'Глава пятая',6:'Глава шестая'};
function chapterName(n){return chapterNames[n]||`Глава ${n}`;}
const editorial={
 '1938-autosphere':{question:'Каким представлялся транспорт, который сможет двигаться сам?',quote:'Будущее транспорта сначала появляется как инженерное воображение — и только потом как задача для следующего поколения.',paras:['В 1938 году Юрий Долматовский пишет об «Автосфере ЗИС‑1001» — автомобиле, которого ещё не существует. Это не инструкция и не прогноз с обещанием точной даты. Это способ проверить инженерную идею через образ будущего.','Для нашего музея важен сам жест: специалист смотрит на ограничения своего времени и задаёт вопрос, каким может стать транспорт, если часть решений возьмёт на себя автоматика. Эта линия потом появится снова — уже в других технологиях, у других людей и в другом контексте.']},
 '1954-radiowaves':{question:'Как связать карту с тем, что машина «видит» вокруг?',quote:'Карта становится не только изображением места — она начинает участвовать в определении положения.',paras:['В «Радиоволнах‑путеводителях» Ф. Честнов описывает радиолокационную картину местности и идею её совмещения с навигационной картой. Для середины XX века это разговор о сигналах, приборах и способах ориентирования.','В центре истории — не конкретный прибор, а вопрос позиционирования: как машине сопоставить модель пространства с реальным окружением. Спустя десятилетия этот вопрос продолжает жить в работе с GPS, Wi‑Fi, сотовыми сетями, датчиками и алгоритмами.']},
 '1956-moving-street':{question:'Как город может помогать движению, а не только принимать его?',quote:'Транспортная идея живёт дольше конкретной формы — меняются люди, интерфейсы и данные вокруг неё.',paras:['Статья С. Вольберга помещает городское движение в пространство инженерной фантазии. Важнее конкретного образа «движущейся улицы» здесь сама попытка представить город как активную систему, которая может организовывать потоки.','Сегодня разговор о движении продолжается уже через данные о светофорах, ритм улиц и понятные подсказки в навигации. Мы не сопоставляем решения; мы наблюдаем, как тема движения остаётся предметом инженерного внимания.']},
 '1956-engineers-dreams':{question:'Что происходит, когда инженер пишет из будущего?',quote:'2056 год сначала появился на журнальной странице — как способ говорить о настоящем через будущее.',paras:['Георгий Бабат в 1956 году выбирает необычную форму: он пишет «отрывки из статей, опубликованных в 2056 году». Будущее здесь становится инструментом разговора об инженерии, а не декорацией.','Эту интонацию мы переносим в финальную главу музея. Не угадывать, что «обязательно случится», а дать сегодняшним разработчикам 2ГИС право сформулировать вопросы, которые они передали бы инженерам следующего поколения.']},
 '1972-evm-moscow':{question:'Когда городской маршрут становится вычислительной задачей?',quote:'Маршрут — это не линия на карте. Это вопрос, который люди учат машину решать.',paras:['В 1972 году «Наука и жизнь» публикует материал «ЭВМ шагает по Москве». В статье транспортная сеть города становится данными, а вычислительная машина получает задачу найти маршрут между точками.','Редакция устраивает эксперимент с букинистическими магазинами Москвы. Для нас важна не гонка человека и машины, а сам момент: городская навигация оказывается задачей, которую можно формализовать, передать алгоритму и продолжать развивать.','Спустя десятилетия этим же классом вопросов занимаются другие люди — уже с дорожным графом, ограничениями, манёврами и новыми пользовательскими сценариями. Эстафета продолжается.']},
 '1980-robot-navigator':{question:'Что нужно машине, чтобы не просто построить путь, а двигаться по нему?',quote:'Планирование, положение и движение соединяются в один навигационный разговор.',paras:['Владимир Тарасенко и Анатолий Кориков рассматривают навигацию как систему связанных задач: спланировать маршрут, определить положение и управлять движением.','В этой истории особенно хорошо видно, почему проект строится вокруг людей. Одни инженеры формулируют структуру задачи в 1980 году; следующие поколения продолжают работать с локализацией уже внутри зданий, подключая компьютерное зрение и мобильные устройства.']},
 '1980-city-tomorrow':{question:'Как инженер говорит о городе, которого ещё нет?',quote:'Будущее становится способом сформулировать вопросы настоящего — и оставить их следующему поколению.',paras:['В 1980 году Виктор Глушков рассуждает о городе завтрашнего дня, автоматизации и вычислительных сетях. Это широкая инженерная перспектива: не один прибор, а целая среда, в которой технологии становятся частью повседневной жизни.','Мы сознательно не подбираем к этой статье современный аналог. Её естественное продолжение — финальная глава 2056, где сегодняшние разработчики 2ГИС смогут так же сформулировать вопросы будущему.']},
 '1984-map-information':{question:'Когда карта становится способом работать с информацией?',quote:'Карта не заканчивается там, где заканчивается изображение. Она может быть интерфейсом к данным о пространстве.',paras:['Александр Берлянт пишет о карте как об информационной модели. Такой взгляд позволяет говорить не только о том, где находится объект, но и о связях между объектами, закономерностях и задачах, которые человек решает через пространство.','Эта линия продолжается в геоаналитике: карта становится рабочей средой, где люди собирают слои, виджеты и дашборды под конкретный вопрос. Не «замена» одной карты другой, а развитие самой идеи карты как инструмента мышления.']},
 '2025-ai-search':{question:'Что меняется, когда поиск начинает работать с намерением человека?',quote:'Городской запрос всё чаще звучит как человеческая фраза, а не как название категории.',paras:['Современная история 2ГИС начинается уже не с бумажного журнала, а с разработчиков и продукта. Поиск учится работать с формулировками, в которых есть контекст, настроение и сценарий.','Это ещё одна точка длинного маршрута: люди продолжают искать способы передать машине больше смысла о городе — не потому, что предыдущие подходы были «хуже», а потому, что меняются сами вопросы.']},
 '2026-easy-routes':{question:'Что ещё может означать «подходящий маршрут»?',quote:'У маршрута есть не только длина и время — у человека есть опыт движения по нему.',paras:['Команда 2ГИС работает с маршрутизацией как с системой множества характеристик. Константин Чирихин рассказывает о сценарии «лёгкого маршрута» и о том, как новые требования становятся частью алгоритмической задачи.','На временной линии музея эта история продолжает тему 1972 года: городской путь остаётся предметом инженерной работы, а люди продолжают уточнять, что именно они хотят доверить алгоритму.']},
 '2026-positioning':{question:'Как навигации жить с неточной координатой?',quote:'Ориентирование начинается не с уверенности, а с умения работать с неопределённостью.',paras:['Спутниковая координата может быть нестабильной. Современная команда навигации работает с несколькими источниками сигнала и механизмами, которые помогают сервису понимать положение человека в городе.','Эта история естественно продолжает вопрос 1954 года о сопоставлении карты и реального пространства — уже без попытки сделать вывод о том, «как далеко мы ушли». В центре остаётся инженерная задача и люди, которые ею занимаются.']},
 '2026-geo-ai':{question:'Можно ли задавать карте вопрос обычными словами?',quote:'Карта становится не только местом, где видны данные, но и средой для разговора о городе.',paras:['В 2ГИС Про появляется работа с геоаналитикой на естественном языке. Пользователь формулирует задачу словами, а система помогает собрать нужные данные и представить их в рабочем виде.','Эта история продолжает линию карты как информационной модели. Меняется способ взаимодействия, но остаётся человеческий вопрос: как сделать пространственные данные понятными и полезными для конкретной задачи.']},
 '2056-next-chapter':{question:'Какой вопрос мы передадим инженерам 2056 года?',quote:'Будущее здесь не финальная точка. Это приглашение следующему человеку продолжить маршрут.',paras:['В 1956 году Георгий Бабат уже использовал 2056 год как литературную и инженерную перспективу. Спустя семьдесят лет мы возвращаемся к этой дате — но не чтобы дать прогноз от имени бренда.','Финальная глава будет собрана из коротких голосов разработчиков 2ГИС: какие задачи они считают открытыми, что кажется невозможным сегодня и о чём они хотели бы спросить инженеров через 30 лет. Это не предсказание. Это передача эстафеты.']}
};
(function(){
  if(!window.MUSEUM_STORIES)return;
  const params=new URLSearchParams(location.search); const id=params.get('id')||'1972-evm-moscow';
  const s=window.MUSEUM_STORIES.find(x=>x.id===id)||window.MUSEUM_STORIES[0];
  const q=sel=>document.querySelector(sel); const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const note=editorial[s.id]||{question:s.subtitle,quote:'Идея продолжает путь, пока её подхватывают люди.',paras:[s.intro]};
  document.title=`${s.year} — ${s.title} · 2ГИС`;
  q('[data-story-kicker]').textContent=`${chapterName(s.chapter)} · ${s.year}`;q('[data-story-title]').textContent=s.title;q('[data-story-deck]').textContent=s.intro;
  q('[data-story-year]').textContent=s.year;q('[data-meta-year]').textContent=s.year;q('[data-meta-source]').textContent=s.source;q('[data-meta-status]').textContent=s.status;q('[data-meta-chapter]').textContent=chapterName(s.chapter);
  q('[data-story-person]').textContent=s.authors?.[0]?.name||'2ГИС';q('[data-story-source]').textContent=s.source;
  q('[data-question]').textContent=note.question;q('[data-story-text]').innerHTML=note.paras.map(p=>`<p>${esc(p)}</p>`).join('');q('[data-story-quote]').textContent=note.quote;
  q('[data-source-link]').href=s.sourceUrl;q('[data-source-link]').textContent=s.sourceUrl==='#'?'Источник будет добавлен':'открыть архив ↗';

  const media=q('[data-story-hero-media]'); const heroImg=s.authors?.find(a=>a.photoUrl)?.photoUrl || s.archive?.coverUrl || s.archive?.pageImages?.[0]?.url;
  if(heroImg){const img=document.createElement('img');img.src=heroImg;img.alt=s.authors?.[0]?.name||s.source;img.addEventListener('error',()=>img.remove());media.prepend(img)}

  const initials=name=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  const artifact=q('[data-artifact-section]'), authorStack=q('[data-author-stack]'), archiveCard=q('[data-archive-card]'), gallery=q('[data-scan-gallery]');
  if((s.authors?.length)||s.archive){artifact.hidden=false;
    authorStack.innerHTML=(s.authors||[]).map(a=>`<article class="author-card">${a.photoUrl?`<img class="author-photo" src="${esc(a.photoUrl)}" alt="${esc(a.name)}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:''}<div class="author-photo author-placeholder" style="${a.photoUrl?'display:none':''}">${esc(initials(a.name))}</div><div class="author-copy"><span class="artifact-label">Автор</span><h3>${a.profileUrl?`<a href="${esc(a.profileUrl)}" target="_blank" rel="noreferrer">${esc(a.name)}</a>`:esc(a.name)}</h3><p>${esc(a.role||'')}</p><small>${esc(a.photoStatus||'')}</small></div></article>`).join('') || '<article class="author-card"><div class="author-photo author-placeholder">—</div><div class="author-copy"><span class="artifact-label">Автор</span><h3>Данные уточняются</h3></div></article>';
    if(s.archive){archiveCard.innerHTML=`<div class="issue-cover ${s.archive.coverUrl?'':'no-image'}">${s.archive.coverUrl?`<img src="${esc(s.archive.coverUrl)}" alt="${esc(s.archive.issueLabel)}" loading="lazy" onerror="this.parentElement.classList.add('image-failed')">`:''}<div class="image-fallback"><div><span>${esc(s.year)}</span><b>Оригинальный выпуск</b></div></div></div><div class="issue-copy"><span class="artifact-label">Оригинальный выпуск</span><h3>${esc(s.archive.issueLabel||s.source)}</h3><p>${esc(s.archive.pagesNote||'')}</p>${s.archive.artifactUrl?`<a href="${esc(s.archive.artifactUrl)}" target="_blank" rel="noreferrer">Открыть скан ↗</a>`:''}<small>${esc(s.archive.rights||'')}</small></div>`;}
    const pages=s.archive?.pageImages||[]; if(pages.length){gallery.innerHTML=`<div class="scan-head"><span>Страницы оригинала</span><small>Сканы используются в прототипе как исследовательский материал</small></div><div class="scan-grid">${pages.map((p,i)=>`<a class="scan-card" href="${esc(s.archive.artifactUrl||s.sourceUrl)}" target="_blank" rel="noreferrer"><div class="scan-image"><img src="${esc(p.url)}" alt="${esc(p.caption||`Страница ${i+1}`)}" loading="lazy" onerror="this.parentElement.classList.add('image-failed')"><div class="scan-fallback">Открыть оригинал ↗</div></div><span>${esc(p.caption||`Страница ${i+1}`)}</span></a>`).join('')}</div>`}
  }

  const handoff=q('[data-continuation]'), route=q('[data-continuation-route]');
  if(s.continuation){handoff.hidden=false;const people=(s.continuation.people||[]).map(p=>`<div class="handoff-person">${p.photoUrl?`<img class="handoff-person-photo" src="${esc(p.photoUrl)}" alt="${esc(p.name)}">`:`<div class="handoff-person-photo handoff-person-placeholder">${esc(initials(p.name))}</div>`}<div>${p.profileUrl?`<a href="${esc(p.profileUrl)}" target="_blank" rel="noreferrer"><b>${esc(p.name)}</b></a>`:`<b>${esc(p.name)}</b>`}<span>${esc(p.role||'')}</span>${p.note?`<small>${esc(p.note)}</small>`:''}</div></div>`).join('');route.innerHTML=`<div class="handoff-stop"><span>${esc(s.year)}</span><b>${esc(s.title)}</b><small>${esc((s.authors||[]).map(a=>a.name).join(' · ')||s.source)}</small></div><div class="handoff-line"><i></i><span>идея продолжает путь</span><i></i></div><div class="handoff-stop handoff-stop-modern"><span>${esc(s.continuation.year)}</span><a class="handoff-article" href="${esc(s.continuation.url)}" target="_blank" rel="noreferrer"><b>${esc(s.continuation.title)}</b><em>Читать на Хабре ↗</em></a><p>${esc(s.continuation.summary||'')}</p><div class="handoff-people">${people}</div></div>`;}

  const live=q('[data-live-visual]');
  if(live){
    if(['route','easy-route','navigator','positioning','moving-city','future-car'].includes(s.visual)){
      live.innerHTML='<div class="motion-route"><svg viewBox="0 0 760 460"><path class="base" d="M40 360 C160 250 210 300 315 215 S510 125 700 80"/><path class="base" d="M60 105 C180 160 240 70 350 150 S540 270 720 205"/><path class="flow" d="M40 360 C160 250 210 300 315 215 S510 125 700 80"/><circle cx="40" cy="360" r="12"/><circle cx="315" cy="215" r="10"/><circle cx="510" cy="125" r="10"/><circle cx="700" cy="80" r="12"/></svg></div>';
    }else if(s.visual==='radar'){
      live.innerHTML='<div class="motion-radar"><i></i><i></i><i></i></div>';
    }else if(['data-map','geo-ai'].includes(s.visual)){
      live.innerHTML='<div class="motion-data">'+Array.from({length:20},()=>'<i></i>').join('')+'</div>';
    }else if(s.visual==='ai-search'){
      live.innerHTML='<div class="motion-ai"><div class="bubble">Найди место, где можно спокойно поговорить и поесть после 22:00</div></div>';
    }else{
      live.innerHTML='<div class="motion-future"><div class="pin"><span>?</span></div></div>';
    }
  }

  const related=q('[data-related-grid]');related.innerHTML=(s.related||[]).map(id=>window.MUSEUM_STORIES.find(x=>x.id===id)).filter(Boolean).map(r=>`<a class="related-card" href="story.html?id=${encodeURIComponent(r.id)}"><b>${esc(r.year)} · ${chapterName(r.chapter)}</b><h3>${esc(r.title)}</h3><span>Открыть историю →</span></a>`).join('');
})();